variable "name" {}
variable "region" {}
variable "vpc-cidr" {}
variable "vpc-dns" {}
variable "vpc-az-public-cider" {}
variable "vpc-az-private-cider" {}
variable "vpc-az-name" {}
variable "client-cidr" {}
variable "client-certificate-filename" {}
variable "client-private-key-filename" {}
variable "server-certificate-filename" {}
variable "server-private-key-filename" {}
variable "ca-certificate-filename" {}
variable "nat-elastic-ip-id" {}
